name: pathopatch_env_fork
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - openslide=3.4.1
  - pip=23.0
  - python-javabridge
  - pip:
    - Pillow==9.5.0
    - PyYAML==6.0
    - Shapely==1.8.5.post1
    - SimpleITK==2.2.1
    - albumentations==1.3.0
    - black==23.1.0
    - csbdeep==0.7.4
    - colorama==0.4.6
    - einops==0.6.1
    - flake8-html==0.4.3
    - flake8==6.0.0
    - future==0.18.2
    - genbadge==1.1.0
    - geojson==3.0.0
    - h5py==3.9.0
    - histolab==0.6.0
    - imageio==2.31.1
    - ipython-genutils==0.2.0
    - jupyterlab==4.0.2
    - kaleido==0.2.1
    - keras==2.12.0
    - keras==2.12.0
    - mako==1.2.4
    - matplotlib==3.7.1
    - natsort==8.4.0
    - numpy>1.22,<1.24
    - opencv_python_headless==4.5.4.58
    - openslide_python==1.2.0
    - pandarallel==1.6.5
    - pandas==1.5.3
    - pre-commit==3.0.3
    - pydantic==1.10.4
    - pyjwt==2.6.0
    - pytest==7.4.4
    - rasterio==1.3.5.post1
    - schema==0.7.5
    - scikit-image==0.19.3
    - scikit-learn==1.2.1
    - scikit-survival==0.21.0
    - scipy>1.5.0,<=1.8.2
    - seaborn==0.12.2
    - sqlalchemy==2.0.17
    - stardist==0.8.5
    - tabulate==0.9.0
    - tensorflow==2.12.0
    - torchinfo==1.8.0
    - torchmetrics==0.11.4
    - torchvision==0.16.2
    - tqdm==4.65.0
    - ujson==5.8.0
    - wandb==0.15.4
