name: pathopatch_env_2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - openslide=3.4.1
  - pip=23.0
  - python-javabridge
  - pip:
    - Pillow>=9.5.0
    - PyYAML
    - Shapely==1.8.5.post1
    - black
    - colorama
    - flake8-html
    - flake8
    - genbadge
    - geojson>=3.0.0
    - matplotlib
    - natsort
    - numpy>1.22,<1.24
    - opencv_python_headless==4.5.4.58
    - openslide_python>=1.3.1
    - pandas
    - pre-commit
    - pydantic==1.10.4
    - pytest==7.4.4
    - pytest-sugar==0.9.7
    - rasterio==1.3.5.post1
    - scikit-image
    - torchvision
    - tqdm
    - wsidicomizer==0.13.2
    - wsidicom==0.20.4
